### ISSUE TITLE
EDTA - unknown issue

### ISSUE THREAD

**Issue by DanJeffries** [oushujun/LTR_FINDER_parallel#2]
Dear Shujun, 

I am very excited to use your pipeline - it looks great from the paper! Unfortunately on my first run I am encountering some errors. I attach the log file from that run in the hope that you can tell me what the issue is. 

Note that I have installed and am running EDTA it on a private server on our cluster. I used conda, although I had to sightly modify the installation instructions. In case that could be the source of the issue, here they are below:

```
mkdir -p /scratch/temporary/djeffrie/condaCache
export CONDA_PKGS_DIRS=/scratch/temporary/djeffrie/condaCache
conda create -y --prefix /scratch/temporary/djeffrie/EDTAcondaenv
conda activate /scratch/temporary/djeffrie/EDTAcondaenv

conda install -y -c conda-forge perl perl-text-soundex multiprocess regex
conda install -y -c cyclus java-jdk
conda install -y -c biocore blast-legacy
conda install -y -c bioconda cd-hit repeatmodeler muscle mdust
conda install -y -c bioconda/label/cf201901 repeatmasker
conda install -y -c anaconda biopython pandas glob2
conda install -y -c anaconda scikit-learn
git clone https://github.com/oushujun/EDTA
./EDTA/EDTA.pl -h
```

The command I used to run EDTA was:
```
perl ../../EDTA/EDTA.pl -genome Rtemp_all_scaffs.fasta -threads 36 > EDTA.log 2>&1 &
```

Many thanks in advance for your help.

Best wishes

Dan

[EDTA.log.gz](https://github.com/oushujun/EDTA/files/3316612/EDTA.log.gz)

**Comment by oushujun** [comment]
Hi Dan,

Thanks for testing EDTA. I am sorry for the inconvenience.

Yes, it's always easier to do things in our own server than to let people use your pipeline - anything can happen in a million ways. We spent a lot of time to make the EDTA pipeline transferrable but there are still a lot of issues. One of the reasons is it tries to combine a number of different pipelines together, which are not necessary bug-free.

From your log file, it seems to be the error of LTR_finder_parallel. Please use your genome to test this pipeline. It's installation free, so just download it and run.

A good practice I should have put in the instruction - always prepare your genome file with simple sequence names - no special characters, just letters and numbers and try to keep them short (i.e., <25 characters).

Please let me know if you encounter any errors.

Best,
Shujun

**Comment by DanJeffries** [comment]
Hi Shujun, 

thanks for the suggestion. I tried LTR_FINDER_parallel on a sequence with name `>000000F-023-01|quiver_obj ALT_Parent:Super-Scaffold_1125` and it failed with similar issues to that in the log file I attached above. Changing the name to `scaff1` solved the issue. So I think you are right that it was just a scaffold naming issue. If not already, it would be useful if you could mention this in the help / tutorial. 

Thanks for your help

Best

Dan

**Comment by DanJeffries** [comment]
Hi Shujun, 

Just to let you know that changing the scaffold names worked so the issue can be closed

Thanks for your help

Dan
