### ISSUE TITLE
header comments in fasta files do bad

### ISSUE THREAD

**Issue by drk0311** [oushujun/LTR_FINDER_parallel#5]
I found the output of LTR_FINDER_parrallel was almost zero after polishing the draft assembly with Racon. 

Before Racon it worked fine but after Racon it went wrong. I found Racon adds comments to the header lines such as contig length and mapped reads used to correct sequences, which seems unexpected for LTR_FINDER_parallel.

So I did  "seqkit seq -i genome.fa" to remove the comments and now it works fine.

Just to let you and some other guys know.
Thanks.

**Comment by oushujun** [comment]
Thanks for the heads up. Yes LTR_DINDER_parallel only supports simple
headers (a-z, 0-9, dash, underscore) at the moment.

Best,
Shujun
