### ISSUE TITLE
need help!

### ISSUE THREAD

**Issue by FiveThousandQW** [oushujun/LTR_FINDER_parallel#8]
the error is :
Tue Mar 22 21:43:24 2022 CPU1: running on CHR1_sub4
open CHR1_sub4 error!
Tue Mar 22 21:43:25 2022 CPU1: CHR1_sub4 timeout, process it with the salvage mode
open CHR1_sub3 error!
Tue Mar 22 21:43:25 2022 CPU2: running on CHR1_sub5
open CHR1_sub5 error!
Tue Mar 22 21:43:25 2022 CPU2: CHR1_sub5 timeout, process it with the salvage mode

l have change the head of sequence to '>chr1'or'>CHR1',but it no work

**Comment by oushujun** [comment]
What was the command used?

**Comment by FiveThousandQW** [comment]
> What was the command used?

like this：perl LTR_FINDER_parallel -seq /home/wuqian/data/genome/Sus_scrofa.Sscrofa11.1.dna.toplevel_3.fa -threads 30

**Comment by FiveThousandQW** [comment]
> What was the command used?



> What was the command used?

The human genome works, but the pig genome doesn't. very weird

**Comment by oushujun** [comment]
try: perl LTR_FINDER_parallel -seq /home/wuqian/data/genome/Sus_scrofa.Sscrofa11.1.dna.toplevel_3.fa -threads 30 -v, then check the files that have errors (eg., CHR1_sub5) in the new directory it creates.

**Comment by FiveThousandQW** [comment]
> try: perl LTR_FINDER_parallel -seq /home/wuqian/data/genome/Sus_scrofa.Sscrofa11.1.dna.toplevel_3.fa -threads 30 -v, then check the files that have errors (eg., CHR1_sub5) in the new directory it creates.

it's not work，but divide the genome full into different chromosomes ，the chr1 can work , the chr2 can not.

the head of chr1 file like this :>chr1
GCTTAATTTTTGTCATTTCTCACCCCTGCTCTTGAGAGCTTTTGTTGATAATGTTGTTATTGCTTTCATTCTGCTTTTAT
TTTGTAAGCCCTGCACTCATTCATCGCTGTACCCGAATATGAGGTAAGGAGTGGTAAAGAAAGACTGGACATAAAAGAGG

the chr2 file like this:>chr2
GAAGTGCCCTGCCAAGTGGCCTAAGTCTTTCTCTCAAGGATTTCAGAGCCCTCAGGCCAACCTGCCCCCAGGCCACTCCT
TTCAAACACGCAGCCGCTCCTCCCGACCCACCAGGTCCTGACAGCCTTCTTCCTTTCTCATAGGGTCCTGCCCTTCTGTC

Is this a problem with my genome files?

**Comment by code0WuQian** [comment]
> > try: perl LTR_FINDER_parallel -seq /home/wuqian/data/genome/Sus_scrofa.Sscrofa11.1.dna.toplevel_3.fa -threads 30 -v, then check the files that have errors (eg., CHR1_sub5) in the new directory it creates.
> 
> it's not work，but divide the genome full into different chromosomes ，the chr1 can work , the chr2 can not.
> 
> the head of chr1 file like this :
> 
> > chr1
> > GCTTAATTTTTGTCATTTCTCACCCCTGCTCTTGAGAGCTTTTGTTGATAATGTTGTTATTGCTTTCATTCTGCTTTTAT
> > TTTGTAAGCCCTGCACTCATTCATCGCTGTACCCGAATATGAGGTAAGGAGTGGTAAAGAAAGACTGGACATAAAAGAGG
> 
> the chr2 file like this:
> 
> > chr2
> > GAAGTGCCCTGCCAAGTGGCCTAAGTCTTTCTCTCAAGGATTTCAGAGCCCTCAGGCCAACCTGCCCCCAGGCCACTCCT
> > TTCAAACACGCAGCCGCTCCTCCCGACCCACCAGGTCCTGACAGCCTTCTTCCTTTCTCATAGGGTCCTGCCCTTCTGTC
> 
> Is this a problem with my genome files?
