### ISSUE TITLE
error in the file *.combine.scn

### ISSUE THREAD

**Issue by ericgonzalezs** [oushujun/LTR_FINDER_parallel#9]
Hello,

I am running LTR_FINDER_parallel like this:

LTR_FINDER_parallel -seq ARG.fa -threads 10 -harvest_out -size 1000000 -time 300

However the file ARG.fa.finder.combine.scn only contains the header. 

#LTR_FINDER_parallel -seq ARG.fa -size 1000000 -time 300 -try1 1 -harvest_out -threads 10 -cut /project/6019339/egonza02/bin/software/LTR_retrieve
r/LTR_FINDER_parallel/LTR_FINDER_parallel/bin/cut.pl -finder /project/6019339/egonza02/bin/software/LTR_retriever/LTR_FINDER_parallel/LTR_FINDER_p
arallel/bin/LTR_FINDER.x86_64-1.0.7/
# LTR_FINDER args=-w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85
# LTR_FINDER_parallel version=v1.2
# predictions are reported in the following way
# s(ret) e(ret) l(ret) s(lLTR) e(lLTR) l(lLTR) s(rLTR) e(rLTR) l(rLTR) sim(LTRs) seq-nr chr
# where:
# s = starting position
# e = ending position
# l = length
# ret = LTR-retrotransposon
# lLTR = left LTR
# rLTR = right LTR
# sim = similarity
# seq-nr = sequence order

I read in another issue that the problem could be the file name. However, I am not sure how short the file name should be. My file name is already very short. Any help with this would be great.

Best Wishes,

Eric

**Comment by oushujun** [comment]
Hi Eric,

Please give some examples of your sequence names in the genome. Thank you.

Shujun

**Comment by mattheatley** [comment]
just to add to this - I had a similar issue that was solved by using simple sequence ids (e.g. seqkit seq --only-id)

**Comment by lijphd168866** [comment]
> just to add to this - I had a similar issue that was solved by using simple sequence ids (e.g. seqkit seq --only-id)

Hello, I have encountered a similar problem. Could I ask how to use （seqkit seq -- only id ）to modify the script?

**Comment by mattheatley** [comment]
just run seqkit beforehand (it's seperate software found here https://github.com/shenwei356/seqkit)

**Comment by oushujun** [comment]
The sequence ID should be no longer than 13 characters composed of letters, numbers, and/or underscore (_), and nothing else. Special characters will confuse the program and also your downstream analyses. I am closing this issue since it's solved.

Best,
Shujun
